### ISSUE TITLE
bit-tabs breaks can-ssr

### ISSUE THREAD

**Issue by marshallswain** [bitovi-components/bit-tabs#13]
The [addPanel and removePanel](https://github.com/bitovi-components/bit-tabs/blob/master/src/unstyled.js#L17) functions are missing from the viewModel when rendered on the SSR server, which prevents the page from being served.

**Comment by justinbmeyer** [comment]
What do you mean missing? Also, I think I've seen it work in the quick start guide.

**Comment by marshallswain** [comment]
If I log the parent().scope/viewModel keys at that line, this is all that shows up:

```
[ '_data',
  '_cid',
  '_computedAttrs',
  'active',
  '%root',
  'title',
  'serialize',
  '_bubbleBindings',
  '__bindEvents',
  '_bindings’ ]
```

No addPanel or removePanel.  If I wrap the call to those functions in an if statement

```
if(this.element.parent().scope().addPanel){
   this.element.parent().scope().addPanel( this.scope );
}
```

Then the server renders the page and the tabs work correctly in the app.  Without that if statement, SSR gives `Potentially unhandled rejection [11] TypeError: this.element.parent(...).viewModel(...).addPanel is not a function`

**Comment by justinbmeyer** [comment]
It wouldn't show up as a key because it's on the prototype. 

I think the problem is that viewModel() isn't returning anything correctly.

**Comment by matthewp** [comment]
I'm seeing this as well when going through the guide, will take a look.

**Comment by matthewp** [comment]
My issue was unrelated: https://github.com/donejs/donejs/issues/444#issuecomment-166338523

Once that is fixed I'll look and see if I'm getting this error or not.
