### ISSUE TITLE
Unable to build after a fresh install.

### ISSUE THREAD

**Issue by m-mujica** [bitovi-components/bit-tabs#7]
I tried to set up this locally but got this error:

![screen shot 2015-08-12 at 10 20 37](https://cloud.githubusercontent.com/assets/724877/9225198/4d849178-40de-11e5-9506-cc449adf204b.png)

Matt pointed out that `bit-tabs` requires a new steal version.

**Comment by matthewp** [comment]
It's not bit-tabs, it's can 2.3.0-pre.7 that needs the latest steal version.
